### PR TITLE
Update the docments

### PR DESCRIPTION
**Pull request by nanqunchen**
1. Update the git submodule command to make the directory the same name as the project.
2. Add a command description on how to demo the example site.

### CODE REVIEW

**Comment by james-s-w-clark** [comment]
This looks great - thanks!
Is it worth saying about how the users should create their own site (copy files from example site to root, change themes directory to ./themes, etc.), where+how to run it, and that they can compare to the example site by running both hugo servers?

**Review by james-s-w-clark — APPROVED** [review]

**Comment by nanqunchen** [comment]
@IdiosApps It may belong to hugo's mechanism but I agree it does help. Please help to add some content to the document if you like. Thanks.

**Comment by james-s-w-clark** [comment]
@nanqunchen I think you phrased it well before. How about this (quick draft)?

---

If you want to have your `content` folder in your root directory, you can copy that from the exampleSite folder to your root directory. In the root directory's `config.toml` you will need to  change the themesdir: `themesdir = "./themes"`. You can now run `hugo server` in the root directory of your project, and Hugo will start your website locally on an available port.

If you want to compare the website from this to the example site, you can start `hugo server` in the exampleSite directory too. Hugo will use different ports, so you can compare the rendered pages with each other. 

To create custom styling, you can create `./static/css/my_style.css`. It will override the theme's styling

---

I added a note on custom styling as it took me little while to figure out where it should go. If it's helpful, I have an example of changing the fonts and table formatting: https://github.com/IdiosApps/IdiosApps.github.io/blob/main/static/css/my_style.css, https://idiosapps.github.io/garden/games-for-socials/

I think it's worth calling out how to compare a user's site to their exampleSite, side-by-side

**Comment by nanqunchen** [comment]
That's great. The css file is also a good add-on. Thanks!
Please create a pull request.
@IdiosApps

**Pull request merged**
